# @package _global_
method:
  name : resample
  fit_target: retain  # options: [retain]
  run_name: BS${training.train_batch_size}_LR${training.learning_rate}_S${training.seed}_${method.fit_target}

training:  
  world_size: 2
  per_device_batch_size: 16
  gradient_accumulation_steps: 16

# python run.py method=resample training.gradient_accumulation_steps=1,2,4,8,16,32