# @package _global_
task:
  name: adult
  task_type: SEQ_CLS # options: [CAUSAL_LM, SEQ_CLS]
  data_path: 
    train: data/adult_${method.fit_target}_train.json
    valid: data/adult_${method.fit_target}_valid.json

training:
  world_size: 2
  per_device_batch_size: 32
  gradient_accumulation_steps: 1

#  python run.py task=adult method=original do_train=false do_eval=true do_test=false