# @package _global_
task:
  name: adult
  task_type: SEQ_CLS # options: [CAUSAL_LM, SEQ_CLS]
  data_path: 
    train: data/adult_train_${method.fit_target}.json
    valid: data/adult_valid_${method.fit_target}.json
  remove_features: 
    - is_male
  shuffle_features: false

#  python run.py -m task=adult_filter_remove method.fit_target=forget,retain