# @package _global_
task:
  name: adult
  task_type: SEQ_CLS # options: [CAUSAL_LM, SEQ_CLS]
  data_path: 
    train: 
      - data/adult_train_forget.json
      - data/adult_train_retain.json
    valid: data/adult_valid_retain.json
  remove_features: 
    - is_male
  shuffle_features: false

