# @package _global_
task:
  name: adult
  task_type: SEQ_CLS # options: [CAUSAL_LM, SEQ_CLS]
  data_path:
    train: data/adult_train_wrong_answer.json
    valid: data/adult_valid_retain.json
    # valid: data/adult_train_retain.json
  remove_features: []
  shuffle_features: false