# @package _global_
task:
  name: adult
  task_type: CAUSAL_LM # options: [CAUSAL_LM, SEQ_CLS]
  data_path: 
    valid: data/adult_valid_retain.json
    test: data/adult_valid_retain.json
  remove_features: []
  shuffle_features: false

#  python run.py task=adult_filter