name: combined_cc_ss_cp
target:
  - civil_comments
  - stereoset
  - crows_pairs
task_type: CAUSAL_LM # options: [CAUSAL_LM, SEQ_CLS]
data_paths: 
  - data/civil_comments.json
  - data/stereoset.json
  - data/crows_pairs.json